function loop_result = mcts_expand_loop_gateway( ...
        use_cpp_loop, ...
        n_expansions_max, ...
        Hp, ...
        root_pose, ...
        reference_trajectory_points, ...
        random_numbers, ...
        all_successor_trims, ...
        maneuvers, ...
        trims, ...
        parents, ...
        children, ...
        shapes_tmp, ...
        n_nodes, ...
        constraint_checker, ...
        constraint_payload ...
    )
    % MCTS_EXPAND_LOOP_GATEWAY  Run MCTS expansion using MEX when available.
    %
    % The MEX interface is intentionally kept the same as the MATLAB fallback
    % to simplify incremental replacement of the expansion loop.

    if nargin < 15
        constraint_payload = struct('mode', 'callback');
    end

    use_mex = use_cpp_loop && (exist('mcts_expand_loop_mex', 'file') == 3);

    if use_mex

        try
            loop_result = mcts_expand_loop_mex( ...
                n_expansions_max, ...
                Hp, ...
                root_pose, ...
                reference_trajectory_points, ...
                random_numbers, ...
                all_successor_trims, ...
                maneuvers, ...
                trims, ...
                parents, ...
                children, ...
                shapes_tmp, ...
                n_nodes, ...
                constraint_checker, ...
                constraint_payload ...
            );
            return
        catch mex_exception
            warning('MonteCarloTreeSearch:MexFallback', ...
                'MEX loop failed (%s). Falling back to MATLAB implementation.', ...
                mex_exception.message);
        end

    end

    loop_result = mcts_expand_loop_matlab( ...
        n_expansions_max, ...
        Hp, ...
        root_pose, ...
        reference_trajectory_points, ...
        random_numbers, ...
        all_successor_trims, ...
        maneuvers, ...
        trims, ...
        parents, ...
        children, ...
        shapes_tmp, ...
        n_nodes, ...
        constraint_checker ...
    );

end
