function tests = mcts_expand_loop_unittest
% MCTS_EXPAND_LOOP_UNITTEST  Regression tests for the extracted MCTS loop.

    tests = functiontests(localfunctions);
end

function testGatewayFallsBackToMatlabAndIsDeterministic(testcase)
    [root_pose, reference_trajectory_points, random_numbers, all_successor_trims, maneuvers, trims, parents, children, shapes_tmp, n_nodes, constraint_checker] = createSyntheticLoopInputs();

    result_a = mcts_expand_loop_gateway( ...
        false, ...
        10, ...
        2, ...
        root_pose, ...
        reference_trajectory_points, ...
        random_numbers, ...
        all_successor_trims, ...
        maneuvers, ...
        trims, ...
        parents, ...
        children, ...
        shapes_tmp, ...
        n_nodes, ...
        constraint_checker ...
    );

    result_b = mcts_expand_loop_gateway( ...
        false, ...
        10, ...
        2, ...
        root_pose, ...
        reference_trajectory_points, ...
        random_numbers, ...
        all_successor_trims, ...
        maneuvers, ...
        trims, ...
        parents, ...
        children, ...
        shapes_tmp, ...
        n_nodes, ...
        constraint_checker ...
    );

    verifyEqual(testcase, result_a.best_node_id, result_b.best_node_id);
    verifyEqual(testcase, result_a.best_cost, result_b.best_cost);
    verifyEqual(testcase, result_a.n_expansions, result_b.n_expansions);
    verifyEqual(testcase, result_a.trims, result_b.trims);
    verifyEqual(testcase, result_a.parents, result_b.parents);
end

function [root_pose, reference_trajectory_points, random_numbers, all_successor_trims, maneuvers, trims, parents, children, shapes_tmp, n_nodes, constraint_checker] = createSyntheticLoopInputs()
    root_pose = [0; 0; 0];
    reference_trajectory_points = [1, 2; 0, 0];
    random_numbers = ones(1, 20);

    all_successor_trims = cell(2, 2);
    all_successor_trims{1, 1} = uint8([1 2]);
    all_successor_trims{1, 2} = uint8([1 2]);
    all_successor_trims{2, 1} = uint8([1 2]);
    all_successor_trims{2, 2} = uint8([1 2]);

    maneuvers = cell(2, 2);
    for start_trim = 1:2
        for goal_trim = 1:2
            maneuver.dpose = [1; 0; 0];
            maneuver.area_without_offset = [0 1 1 0; 0 0 1 1];
            maneuver.area = [0 1 1 0; 0 0 1 1];
            maneuver.area_large_offset = [0 1 1 0; 0 0 1 1];
            maneuvers{start_trim, goal_trim} = maneuver;
        end
    end

    trims = zeros(1, 11, 'uint8');
    trims(1) = 1;
    parents = zeros(1, 11, 'uint32');
    children = zeros(2, 11, 'uint32');
    children(:, 1) = uint32([1; 1]);
    shapes_tmp = cell(1, 11);
    n_nodes = 1;

    constraint_checker = @(~, ~, ~) true;
end
